version: '3'

services:

  influxdb:
    image: 'influxdb:${INFLUXDB_VERSION}'
    container_name: 'influxdb'
    ports: 
      - 8086:8086
      - 8088:8088
    volumes:
      - ${DCDATADIR}/influxdb:/var/lib/influxdb
      - ${DCDATADIR}/logs/influxdb:/var/log/influxdb
      - ${DCDEVDIR}/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ${DCDEVDIR}/influxbackupdump/:/home/influxbackups/
    networks:
      - default
    user: ${DCUSERID}:${DCGRPID}
    restart: always

  telegraf:
    build: 
      context: '.'
      dockerfile: 'telegrafDockerfile'
      args:
        - version=${TELEGRAF_VERSION}
        - userid=${DCUSERID}
        - groupid=${DCGRPID}
        - dockergid=${DCDOCKERID}
    image: 'telegraf/telegrafuserland:${TELEGRAF_VERSION}'
    container_name: 'telegraf'
    privileged: true
    environment:
          HOST_PROC: /rootfs/proc
          HOST_SYS: /rootfs/sys
          HOST_ETC: /rootfs/etc
    hostname: telegrafDocker
    volumes:
          - ${DCDATADIR}/logs/telegraf/:/var/log/
          - ${DCDEVDIR}/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
          - /sys:/rootfs/sys:ro
          - /proc:/rootfs/proc:ro
          - /etc:/rootfs/etc:ro
          - /var/run/utmp:/var/run/utmp
          - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - 'influxdb'
    networks:
      - default
#    user: ${DCUSERID}
    restart: always

  chronograf:
    image: 'chronograf:${CHRONOGRAF_VERSION}'
    container_name: 'chronograf'
    ports: 
      - 8888:8888
    volumes:
      - ${DCDATADIR}/logs/chronograf:/var/log/chronograf
      - ${DCDATADIR}/chronograf:/var/lib/chronograf
    depends_on:
      - "influxdb"
      - "telegraf"
    networks:
      - default
    user: ${DCUSERID}:${DCGRPID}
    restart: always

  grafana:
    build: 
      context: ./
      dockerfile: 'grafanaDockerfile'
      args:
        - GRAFANA_VERSION=${GRAFANA_VERSION}
        - GF_PLUGIN_NEWPATH=/home/grafana/plugins/
        - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,natel-discrete-panel,vonage-status-panel,fetzerch-sunandmoon-datasource,ryantxu-ajax-panel,jdbranham-diagram-panel,natel-plotly-panel,fatcloud-windrose-panel,michaeldmoore-annunciator-panel,blackmirror1-statusbygroup-panel,natel-influx-admin-panel,andig-darksky-datasource,grafana-polystat-panel,flant-statusmap-panel,mtanda-histogram-panel
    image: 'grafana/grafana:${GRAFANA_VERSION}_wplugs'
    container_name: 'grafana'
    ports:
      - 3000:3000
    volumes:
      - ${DCDEVDIR}/config/grafana.ini:/etc/grafana/grafana.ini
      - ${DCDATADIR}/grafana/:/var/lib/grafana/
      - ${DCDATADIR}/logs/grafana:/var/log/grafana
    depends_on:
      - 'influxdb'
      - 'telegraf'
    networks:
      - default
    user: ${DCUSERID}:${DCGRPID}
    restart: always

  home-assistant:
    container_name: home-assistant
    ports: 
      - 8123:8123
    image: homeassistant/raspberrypi3-homeassistant:${HOMEASSISTANT_VERSION}
    volumes:
      - /home/pi/DockerData/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - 'influxdb'
      - 'telegraf'
      - 'grafana'
    networks:
      - default
    restart: always

networks:
    default:
        driver: bridge
